# encoding: utf-8
#
#-
# Bulk delete Assets using CSV generated by listOlderAssets.py
# Created by P. Alexander 7/28/2022 
#

import csv
from lxml import objectify

import qualysapi 

#-
# Initialize variables
#
DATA_FILE = "livetest.csv"

#-
# Build dictionary, then convert that into a comma-separated list that is usable by the API
#
def parse_csv():
   with open(DATA_FILE, newline='') as csvfile:
      ip_dict = csv.DictReader(csvfile)
      build_list = ",".join([row["IP"] for row in ip_dict])
      print("List Built. Exporting data.")
   return build_list

#- 
# Assign the list -DATA- to a variable for later use
#
purge_list = parse_csv()

# Debugging statement
#print("Returned list",purge_list)

def purge_asset_data():

   #Debug/testing ONLY
   print("List to be purged:",purge_list,"\n")
   input("Continue? [y/N]")
   
   try:
     a = qualysapi.connect('config.ini')
     assets = a.request('/api/2.0/fo/asset/host/',{
         'action':'purge',
         'data_scope':'pc,vm',
         'ips':purge_list,
         },verify=False)  # Prevent 'Self-Signed Certificate in Chain' from blocking activity
     print(assets)
     
   except AttributeError:
      print("error", "Can't find the data")

purge_asset_data()