# encoding: utf-8
#-
# Bulk delete Assets using CSV generated by listOlderAssets.py
# Original Source: https://github.com/SBB-Mx/Qualys
#

import qualysapi 
import sys, datetime
from datetime import date
from lxml import objectify
from datetime import datetime
from datetime import timedelta
import logging
logging.basicConfig()
logger = logging.getLogger('logger')

#-
# Initialize Variables
#
day = (datetime.today()  - timedelta(days=int(sys.argv[1])) ).strftime('%Y-%m-%d')
getday = date.today()
today = getday.strftime('%Y-%m-%d')
tags = str(sys.argv[2])


def purge(days,tags,today):
	try:
		a = qualysapi.connect('config.ini')
		assets = a.request('/api/2.0/fo/asset/host/',{
		'action':'list',
		'details':'All/AGs',
		'no_vm_scan_since':days,
		'use_tags':'1',
		'tag_set_by':'name',
		'tag_set_include':tags,
		},verify=False)  # Prevent 'Self-Signed Certificate in Chain' from blocking activity         

		#print(assets)
		root = objectify.fromstring(assets.encode('utf-8'))
		file = open("asset-list-" + tags + "-" + today +".csv","w+")
		file.write("Host ID,IP,DNS Name,OS,Tracking,Last vuln scan"'\n')
		for host in root.RESPONSE.HOST_LIST.HOST:
			#print ('\n'"++++++++++++++++++++++++++++++++++++++++"'\n')
			try: 
				#print ("Host ID: "+host.ID.text)
				file.write(host.ID.text+",")
			except AttributeError:
				print ("NO HOST ID ")
				file.write("NO HOST ID"+",")
			try: 
				#print ("IP: "+host.IP.text)
				file.write(host.IP.text+",")
			except AttributeError:
				#print ("NO IP ")
				file.write("NO IP"+",")
			try: 
				#print ("DNS: "+host.DNS.text)
				file.write(host.DNS.text+",")
			except AttributeError:
				#print ("NO DNS ")
				file.write("NO DNS"+",")
			try:
				#print ("OS: "+host.OS.text)
				file.write(host.OS.text+",")
			except AttributeError:
				print ("No OS")
				file.write("No OS"+",")				
			try:
				#print ("Tracking: "+host.TRACKING_METHOD.text)
				file.write(host.TRACKING_METHOD.text+",")
			except AttributeError:
				#print ("No TRACKING_METHOD")
				file.write("NO TRACKING_METHOD"+",")
				
			#print ("Last scanned: "+host.LAST_VULN_SCAN_DATETIME.text)
			file.write(host.LAST_VULN_SCAN_DATETIME.text+'\n')
			#print ('\n'"++++++++++++++++++++++++++++++++++++++++"'\n')
		file.close()
	except AttributeError:
		print("error", "I don't find data for host not scanned since "+ days)	

#-
# Do the thing
#
purge(day,tags,today)

