# encoding: utf-8
#
#-
# Bulk delete Assets using CSV generated by listOlderAssets.py
# Created by P. Alexander 7/28/2022 
#

import csv
from lxml import objectify

import qualysapi 

#-
# Initialize variables
#
DATA_FILE = "ticket_test.csv"

#-
# Build dictionary, then convert that into a comma-separated list that is usable by the API
#
def parse_csv():
   with open(DATA_FILE, newline='',) as csvfile:
      ticket_list = csv.DictReader(csvfile)
      for row in ticket_list:
         qid = row['QID']
         ticket = row['Ticket']
         print('Sending Data \n' + 'QID: ' + qid + '\nTicket: ' + ticket)
         
         callAPI()
   return qid,ticket

qid, ticket = parse_csv()

#-
# API Call
#
def callAPI(qid,ticket):
   a = qualysapi.connect('config.ini')
   assets = a.request('/api/2.0/fo/knowledge_base/vuln/',{
         'action':'edit',
         'qid':qid,
         'solution_comment':'Jira Ticket: ' + ticket,
      },verify=False)  # Prevent 'Self-Signed Certificate in Chain' from blocking activity
   
   # Print Full API response
   print(assets)

#-
# Run
#
#callAPI(qid,ticket)


