# encoding: utf-8
#
#-
# Bulk delete Assets using CSV generated by listOlderAssets.py
# Created by P. Alexander 7/28/2022 
#

import csv
from lxml import objectify

import qualysapi 

#-
# Initialize variables
#
DATA_FILE = "ticket_list.csv"

#-
# Build dictionary, then convert that into a comma-separated list that is usable by the API
#
def parse_csv():
   with open(DATA_FILE, newline='',) as csvfile:
      ticket_list = csv.DictReader(csvfile)
      for row in ticket_list:
         qid = row['QID']
         ticket = row['Ticket']
         build_list = qid + ' ' + comment + ticket
      print('List Built. Exporting data.')
#      callAPI()
   return build_list

#- 
# Assign the list -DATA- to a variable for later use
#
ticket_list = parse_csv()

# Debugging statement
print("Returned list",ticket_list)

#-
# API Call
#
def callAPI():
      a = qualysapi.connect('config.ini')
      assets = a.request('/api/2.0/fo/asset/host/',{
         'action':'edit',
         'qid':qid,
         'solution_comment':'Jira Ticket: ' + ticket,
      },verify=False)  # Prevent 'Self-Signed Certificate in Chain' from blocking activity