# encoding: utf-8
#
#-
# Bulk delete Assets using CSV generated by listOlderAssets.py
# Created by P. Alexander 7/28/2022 
#

import csv
from lxml import objectify

import qualysapi 

#-
# Initialize variables
#
DATA_FILE = "ticket_list.csv"

#-
# Build dictionary, then convert that into a comma-separated list that is usable by the API
#
def parse_csv():
   with open(DATA_FILE, newline='',) as csvfile:
      ticket_list = csv.reader(csvfile)
      for row in ticket_list:
         qid = int(row['QID'])
         ticket = row['Ticket']
      build_list = qid + ',' + ticket
      print('List Built. Exporting data.')
   return build_list

#- 
# Assign the list -DATA- to a variable for later use
#
purge_list = parse_csv()

# Debugging statement
print("Returned list",purge_list)

#-
# API Call
#/api/2.0/fo/knowledge_base/vuln/ --> action=edit&solution_comment="Jira ticket: [ticket]&qid=[qid]"